### ISSUE TITLE
controller panic

### ISSUE THREAD

**Issue by rink1969** [cita-cloud/controller_poc#36]
2021-03-26T08:12:02.189176192+00:00 ERROR controller::panic_hook -
============================
   0: controller::panic_hook::panic_hook
             at /build/src/panic_hook.rs:39:21
   1: core::ops::function::Fn::call
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   7: core::slice::index::slice_end_index_len_fail
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/index.rs:41:5
   8: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/index.rs:238:13
      <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/index.rs:284:9
      core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/index.rs:15:9
      <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:2161:9
      controller::controller::Controller::rpc_get_block_by_hash::{{closure}}::{{closure}}
             at /build/src/controller.rs:247:46
      core::result::Result<T,E>::map
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/result.rs:508:25
      controller::controller::Controller::rpc_get_block_by_hash::{{closure}}
             at /build/src/controller.rs:242:28
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
      <controller::RPCServer as cita_cloud_proto::controller::rpc_service_server::RpcService>::get_block_by_hash::{{closure}}
             at /build/src/main.rs:174:9
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/future.rs:119:9
      <<cita_cloud_proto::controller::rpc_service_server::RpcServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::GetBlockByHashSvc<T> as tonic::server::service::UnaryService<cita_cloud_proto::common::Hash>>::call::{{closure}}
             at /build/target/release/build/cita_cloud_proto-65eef919d627b9fe/out/controller.rs:540:52
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/future.rs:119:9
      tonic::server::grpc::Grpc<T>::unary::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.4.1/src/server/grpc.rs:82:24
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
      <cita_cloud_proto::controller::rpc_service_server::RpcServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
             at /build/target/release/build/cita_cloud_proto-65eef919d627b9fe/out/controller.rs:555:35
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/future.rs:119:9
      <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.13/src/future.rs:84:9
      <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/try_future/into_future.rs:35:9
      <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/map.rs:55:37
  12: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
      <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
      <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/either.rs:72:32
      <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.13/src/future.rs:84:9
      <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/try_future/into_future.rs:35:9
      <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/map.rs:55:37
  13: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
      <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
      <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/either.rs:73:33
      <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.13/src/future.rs:84:9
      <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/try_future/into_future.rs:35:9
      <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/map.rs:55:37
  14: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
      <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
      <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/either.rs:73:33
      <tower::util::either::Either<A,B> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.6/src/util/either.rs:71:57
  15: <tower::util::either::Either<A,B> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.6/src/util/either.rs:71:57
      <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  16: <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.13/src/future.rs:84:9
      <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/try_future/into_future.rs:35:9
      <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/future/future/map.rs:55:37
  17: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
      <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/lib.rs:102:13
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/future.rs:119:9
      hyper::proto::h2::server::H2Stream<F,B>::poll2
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.4/src/proto/h2/server.rs:375:37
      <hyper::proto::h2::server::H2Stream<F,B> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.4/src/proto/h2/server.rs:437:9
  19: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/core.rs:225:13
      tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/harness.rs:422:23
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:322:9
      std::panicking::try::do_call
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
      tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/harness.rs:409:19
  20: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/harness.rs:89:9
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/task/harness.rs:59:15
  21: std::thread::local::LocalKey<T>::with
  22: tokio::runtime::thread_pool::worker::Context::run_task
  23: tokio::runtime::thread_pool::worker::Context::run
  24: tokio::macros::scoped_tls::ScopedKey<T>::set
  25: tokio::runtime::thread_pool::worker::run
  26: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  27: std::panicking::try
  28: tokio::runtime::task::harness::Harness<T,S>::poll
  29: std::sys_common::backtrace::__rust_begin_short_backtrace
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
  31: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/unix/thread.rs:71:17
  32: start_thread
  33: clone

position:
Thread tokio-runtime-worker panicked at range end index 8 out of range for slice of length 0, src/controller.rs:247
============================

**Comment by rink1969** [comment]
storage那边在查询不到对应的key的时候是直接返回空vec，而不是报错。
controller这边没有针对这个情况进行处理，所以直接panic了。

**Comment by rink1969** [comment]
修改之后，初始化起不来了。
一直在报：
```
get current block number failed! Retrying
```

终于想起来为什么 storage那边在查询不到对应的key的时候是直接返回空vec，而不是报错？
就是为了新链起来的时候，区分出数据库是空的，还是连接等等有问题。

所以前面的`pr`合并之后，初始化的地方要做个对应的修改。
